image:
  file: .gitpod.dockerfile

tasks:
  - name: Prep
    init: |
      npm install &&
      npm install -g ts-node &&
      ts-node init.ts
    command: npm run dev

vscode:
  extensions:
    - Prisma.prisma
