image:
  file: .gitpod.dockerfile

gitConfig:
  alias.s: status
  alias.co: checkout
  alias.fa: fetch --all

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: false
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    addCheck: false

ports:
  - port: 8080
    onOpen: ignore

  - port: 5050
    onOpen: ignore

  - port: 5432
    onOpen: ignore

  - port: 1337
    onOpen: ignore

tasks:
  - name: Prep
    init: |
      npm install &&
      docker-compose up -d &&
      cat .env.sample > .env

vscode:
  extensions:
    - Prisma.prisma
    - esbenp.prettier-vscode
    - rangav.vscode-thunder-client
    - dbaeumer.vscode-eslint
    - Orta.vscode-jest
