image:
  file: .gitpod.dockerfile

gitConfig:
  alias.s: status
  alias.co: checkout
  alias.fa: fetch --all

ports:
  - port: 8080
    onOpen: ignore

  - port: 5050
    onOpen: ignore

  - port: 5432
    onOpen: ignore

  - port: 1337
    onOpen: ignore

tasks:
  - name: Prep
    init: |
      npm install &&
      npm install -g ts-node &&
      ts-node init.ts
    command: npm run dev

vscode:
  extensions:
    - Prisma.prisma
    - esbenp.prettier-vscode
    - rangav.vscode-thunder-client
    - dbaeumer.vscode-eslint
